### ISSUE TITLE
Git Process Changes

### ISSUE THREAD

**Issue by Thomastppt** [calgarytospace/OBC_software#7]
To Do:
-Create a base branch (development/main) that is the bare bones stm32 project with FreeRtos enabled and UART Ports enabled
-From the base branch, make separate branches (development/module/x.xx) for the new modules
-Pushes to development/module/x.xx do not need reviews but pull requests back into development/main will need 3 reviewers before it is approved

**Comment by NuclearTea** [comment]
Need to clean up branches, do we need james_training?

RESOLVED

**Comment by NuclearTea** [comment]
Need to create base branch, that will be the basis of all other modules' branches.
- [ ] Get people's current work onto GitHub somewhere
- [ ] Get people to comment, push, and have good commit messages to their branches
- [ ] Create Base Branch
- [ ] Integrate camera module into base branch
- [ ] Integrate other previous modules and relevant work into base branch
- [ ] Check whether the integration of all relevant work works as intended
- [ ] Get people to branch out from base branch (with their own branches), could be personal if individual work or module name for group work

Overall, the point of this is to better organize our code and to set ourselves up for success moving forward. For example: doing testing and setting up tests will be much easier and efficient if we know where everything is and if people can work together more efficiently.

**Comment by NuclearTea** [comment]
Changing Plans, doing simple git branch strategy
